### ISSUE TITLE
SOL Enablement in Daytonax 

### ISSUE THREAD

**Issue by jdhanasekar** [AMDESE/amd-power-control#3]
Hi AMD,

I am working on to enable SOL in Daytonax Server.  
Which UART is used for SOL feature, Virtual UART or UART muxing ?.

Can you please provide me info?

**Comment by supven01** [comment]
[AMD Official Use Only]

UART 5

Thanks,
Supreeth Venkatesh
System Manageability Architect  |  AMD
Server Software
***@***.***D7560B.303556F0]

From: jdhanasekar ***@***.***>
Sent: Monday, May 31, 2021 7:16 AM
To: AMDESE/amd-power-control ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AMDESE/amd-power-control] SOL Enablement in Daytonax (#3)

[CAUTION: External Email]

Hi AMD,

I am working on to enable SOL in Daytonax Server.
Which UART is used for SOL feature, Virtual UART or UART muxing ?.

Can you please provide me info?

-

**Comment by jdhanasekar** [comment]
As per Schematic, UART 5 is for BMC console. Same is used for SOL ?. If possible, share the diagram of SoL Hardware Design. 
In my case, BMC is not receiving serial data from Host.
